{application, gdserver,
  [{description,  "Gorod Dorog server application"},
   {vsn,          "1.0"},
   {modules,      [allTest, authorizationTest, backuper, bot, carUpgrades, cityManager, client, 
					clientTest, dbActivity, dbAdvertisement, dbGame, dbGlobal, dbItem, dbMessage,
					dbOnlineStats, dbSession, dbUser, dbUserProgress, dbUuid, editor, fileUpload, 
					flashSecurity, fuel, fuelTest, futil, gdapp, globalChat, 
					globalChatTest, helper, itemEditorView, lobby, lobbyManager, lobbyManagerTest, 
					lobbyTest, lobbyTestF, log, logWatcher, migration_44, 
					migrator, mneser, mneserTest, notConnectedTest, protocol, 
					queryCache, quickTest, raceManagerTest, racingTest, routeEditorView, server, serverSocket, sms, 
					smsTest, smtp, socket, statistics, stats, statsTest, status, stressTest, systemStats,
					tableEditorView, temp, userAdmin, users, usersTest, utils, utilsTest, 
					vkontakte, ymnesia]},
   {registered,   [log, queryCache, vkontakte, lobbyManager1, lobbyManager2, 
					logWatcher, globalChat, backuper, serverSocket, flashSecurity1, flashSecurity2]},
   {applications, [kernel, stdlib]},
   {mod,          {gdapp, ["./cfg/"]}}]}.